
// This file has been generated by the GUI designer. Do not modify.
namespace Ereadian.PowerPointRemoteController.Client
{
	public partial class MainWindow
	{
		private global::Gtk.HBox MainArea;
		
		private global::Gtk.VBox ContentArea;
		
		private global::Gtk.TextView ContentBox;
		
		private global::Gtk.Entry MessageLine;
		
		private global::Gtk.VBox ControlArea;
		
		private global::Gtk.Button NextPageButton;
		
		private global::Gtk.Button PrevPageButton;
		
		private global::Gtk.Label TimeLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Ereadian.PowerPointRemoteController.Client.MainWindow
			this.Name = "Ereadian.PowerPointRemoteController.Client.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Ereadian.PowerPointRemoteController.Client.MainWindow.Gtk.Container+ContainerChild
			this.MainArea = new global::Gtk.HBox ();
			this.MainArea.Name = "MainArea";
			this.MainArea.Spacing = 6;
			// Container child MainArea.Gtk.Box+BoxChild
			this.ContentArea = new global::Gtk.VBox ();
			this.ContentArea.Name = "ContentArea";
			this.ContentArea.Spacing = 6;
			// Container child ContentArea.Gtk.Box+BoxChild
			this.ContentBox = new global::Gtk.TextView ();
			this.ContentBox.Sensitive = false;
			this.ContentBox.Name = "ContentBox";
			this.ContentArea.Add (this.ContentBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.ContentArea [this.ContentBox]));
			w1.Position = 0;
			// Container child ContentArea.Gtk.Box+BoxChild
			this.MessageLine = new global::Gtk.Entry ();
			this.MessageLine.Sensitive = false;
			this.MessageLine.CanFocus = true;
			this.MessageLine.Name = "MessageLine";
			this.MessageLine.IsEditable = true;
			this.MessageLine.InvisibleChar = '•';
			this.ContentArea.Add (this.MessageLine);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ContentArea [this.MessageLine]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.MainArea.Add (this.ContentArea);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.MainArea [this.ContentArea]));
			w3.Position = 0;
			// Container child MainArea.Gtk.Box+BoxChild
			this.ControlArea = new global::Gtk.VBox ();
			this.ControlArea.Name = "ControlArea";
			this.ControlArea.Spacing = 6;
			// Container child ControlArea.Gtk.Box+BoxChild
			this.NextPageButton = new global::Gtk.Button ();
			this.NextPageButton.CanFocus = true;
			this.NextPageButton.Name = "NextPageButton";
			this.NextPageButton.UseUnderline = true;
			this.NextPageButton.Label = global::Mono.Unix.Catalog.GetString ("Next");
			this.ControlArea.Add (this.NextPageButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ControlArea [this.NextPageButton]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child ControlArea.Gtk.Box+BoxChild
			this.PrevPageButton = new global::Gtk.Button ();
			this.PrevPageButton.CanFocus = true;
			this.PrevPageButton.Name = "PrevPageButton";
			this.PrevPageButton.UseUnderline = true;
			this.PrevPageButton.Label = global::Mono.Unix.Catalog.GetString ("Previous");
			this.ControlArea.Add (this.PrevPageButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ControlArea [this.PrevPageButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child ControlArea.Gtk.Box+BoxChild
			this.TimeLabel = new global::Gtk.Label ();
			this.TimeLabel.Name = "TimeLabel";
			this.TimeLabel.LabelProp = "00:00";
			this.ControlArea.Add (this.TimeLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.ControlArea [this.TimeLabel]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.MainArea.Add (this.ControlArea);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.MainArea [this.ControlArea]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.MainArea);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 536;
			this.DefaultHeight = 334;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.NextPageButton.Clicked += new global::System.EventHandler (this.OnNextPage);
			this.PrevPageButton.Clicked += new global::System.EventHandler (this.OnPreviousPage);
		}
	}
}
