
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox MainArea;
	
	private global::Gtk.TextView ContentView;
	
	private global::Gtk.VBox ControlArea;
	
	private global::Gtk.Button NextPage;
	
	private global::Gtk.Button PrevPage;
	
	private global::Gtk.Label TimeLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainArea = new global::Gtk.HBox ();
		this.MainArea.Name = "MainArea";
		this.MainArea.Spacing = 6;
		// Container child MainArea.Gtk.Box+BoxChild
		this.ContentView = new global::Gtk.TextView ();
		this.ContentView.CanFocus = true;
		this.ContentView.Name = "ContentView";
		this.ContentView.Editable = false;
		this.ContentView.CursorVisible = false;
		this.MainArea.Add (this.ContentView);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.MainArea [this.ContentView]));
		w1.Position = 0;
		// Container child MainArea.Gtk.Box+BoxChild
		this.ControlArea = new global::Gtk.VBox ();
		this.ControlArea.Name = "ControlArea";
		this.ControlArea.Spacing = 6;
		// Container child ControlArea.Gtk.Box+BoxChild
		this.NextPage = new global::Gtk.Button ();
		this.NextPage.CanFocus = true;
		this.NextPage.Name = "NextPage";
		this.NextPage.UseUnderline = true;
		this.NextPage.Label = global::Mono.Unix.Catalog.GetString ("Next");
		this.ControlArea.Add (this.NextPage);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ControlArea [this.NextPage]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child ControlArea.Gtk.Box+BoxChild
		this.PrevPage = new global::Gtk.Button ();
		this.PrevPage.CanFocus = true;
		this.PrevPage.Name = "PrevPage";
		this.PrevPage.UseUnderline = true;
		this.PrevPage.Label = global::Mono.Unix.Catalog.GetString ("Previous");
		this.ControlArea.Add (this.PrevPage);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ControlArea [this.PrevPage]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child ControlArea.Gtk.Box+BoxChild
		this.TimeLabel = new global::Gtk.Label ();
		this.TimeLabel.Name = "TimeLabel";
		this.TimeLabel.LabelProp = "00:00";
		this.ControlArea.Add (this.TimeLabel);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ControlArea [this.TimeLabel]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.MainArea.Add (this.ControlArea);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MainArea [this.ControlArea]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.Add (this.MainArea);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 536;
		this.DefaultHeight = 334;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.NextPage.Clicked += new global::System.EventHandler (this.OnNextPage);
		this.PrevPage.Clicked += new global::System.EventHandler (this.OnPreviousPage);
	}
}
